[package]
name = "serde-json-example"
version = "0.1.0"
authors = ["markjordilew <mark.lewis@zappistore.com>"]

[dependencies]
serde="0.9"
serde_derive="0.9"
serde_json="0.9"
regex="0.2.1"
chrono="0.4.0"
